# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7c37139a-d431-42c5-94cc-30d2927ec731";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/70F1-F75C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    }; 

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c05b976b-fb00-42cd-b341-841923fa78f4"; }
    ];

  # fileSystems."/media/storage" = {
  #   device = "/dev/disk/by-uuid/24F52C3B1DBA0C27";
  #   options = ["nofail" "x-systemd.automount" "uid=1000" "gid=1000" "dmask=007" "fmask=117"];
  # };

  # fileSystems."/media/ext_storage" = {
  #   device = "/dev/disk/by-uuid/F474B7AA74B76DCC";
  #   options = ["nofail" "x-systemd.automount" "uid=1000" "gid=1000" "dmask=007" "fmask=117"];
  # };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  services.logind.lidSwitch = "ignore";
}
